server:
  port: 9090

spring:
  application:
    name: APIGatewayService
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://AccountService
          predicates:
            - Path=/api/v1/auth/**
        - id: item-service
          uri: lb://ItemService
          predicates:
            - Path=/api/items,/api/items/**
        - id: order-service
          uri: lb://OrderService
          predicates:
            - Path=/api/orders,/api/orders/**
        - id: cart-service
          uri: lb://CartService
          predicates:
            - Path=/api/cart,/api/cart/**
        - id: payment-service
          uri: lb://PaymentService
          predicates:
            - Path=/api/payments/**

        # API docs routes for Swagger aggregation
        - id: account-service-api-docs
          uri: lb://AccountService
          predicates:
            - Path=/account/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: item-service-api-docs
          uri: lb://ItemService
          predicates:
            - Path=/item/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: order-service-api-docs
          uri: lb://OrderService
          predicates:
            - Path=/order/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: cart-service-api-docs
          uri: lb://CartService
          predicates:
            - Path=/cart/v3/api-docs/**
          filters:
            - StripPrefix=1
        - id: payment-service-api-docs
          uri: lb://PaymentService
          predicates:
            - Path=/payment/v3/api-docs/**
          filters:
            - StripPrefix=1

app:
  jwt-secret: JWTSecretKey12345678901234567890123456789012

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: Account Service
        url: /account/v3/api-docs
      - name: Item Service
        url: /item/v3/api-docs
      - name: Order Service
        url: /order/v3/api-docs
      - name: Cart Service
        url: /cart/v3/api-docs
      - name: Payment Service
        url: /payment/v3/api-docs
