version: '3.9'

services:
  payment-postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_USER: paymentapp
      POSTGRES_PASSWORD: paymentpass
      POSTGRES_DB: paymentdb
    ports:
      - "5434:5432"
    volumes:
      - payment-pg-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentapp -d paymentdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shop-net

  payment-kafka:
    image: apache/kafka:3.7.0
    container_name: payment-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://payment-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@payment-kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "29092:29092"
    networks:
      - shop-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: payment-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: payment-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: payment-kafka:9092
    depends_on:
      - payment-kafka
    networks:
      - shop-net

volumes:
  payment-pg-data:

networks:
  shop-net:
    driver: bridge
